name: Mdbook build

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: '0.4.34'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install mdbook
      run: |
        mkdir ~/tools
        curl -L https://github.com/rust-lang/mdBook/releases/download/v$MDBOOK_VERSION/mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/tools
    - name: Build
      run: mdbook build
    # share between different jobs
    - uses: actions/upload-artifact@v3
      with:
        name: book
        path: book/
